name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag guo40020/my-theia
    
    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: guo40020
        password: ${{secrets.DOCKER_PWD}}

    - name: push
      run: docker push guo40020/my-theia
      
